Feature/#5 create header component
mp-gumi/training-kaneko-1 pull request #16
Opened 2021-09-06 05:26 UTC by mp-gumi

close #5

2021-09-06 06:57 UTC, mp-gumi commented
@piro0919 よろしくお願いします 🙏

2021-09-06 07:44 UTC, piro0919 commented
@mp-gumi 

この PR でスタイリングまで全て入れちゃいましょう。 👍

2021-09-08 07:45 UTC, mp-gumi commented
@piro0919
確認よろしくお願いします。 🙏

2021-09-08 07:52 UTC, piro0919 requested changes
全体的には良い感じです。 😸 

重複する指摘は省いているので、全体的に見返して直してみてください。 👍

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/HamburgerBar/index.tsx
> +type HamburgerBarProps = {
[imo]

export があったほうがいいですね。 👍

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/HamburgerBar/index.tsx
> +  const { isOpen, setIsOpen } = props;
[imo]

オブジェクトへのアクセスはワンライナーで書けますね。 🐶 

`const HamburgerBar = ({ isOpen, setIsOpen }: HamburgerBarProps) => {`

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/HamburgerBar/index.tsx
> +  const handleClick = () => {
[nits]

`useCallback` でくくっちゃっても問題ないですね。

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/HamburgerBar/index.tsx
> +          background-color: #000000;
[imo]

短縮形のほうが好ましいですね。 🦢 

`#000`

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/Logo/index.tsx
> +    <Link to={"/"}>
[must]

普通に文字列でだいじょーぶです。 👀 

`<Link to="/">`

2021-09-08 07:52 UTC, piro0919 commented on src/components/Header/Menu/index.tsx
> +  const items = [
[nits]

`useMemo` 入れても良いですね。 👍

2021-09-08 09:19 UTC, mp-gumi commented
@piro0919
アドバイスいただいた箇所を修正しました！ありがとうございます 👍 
質問なのですが、
・useMemoおよびuseCallbackの第二引数には何を入れたらいいか(あるいは、空のままでもいいのか)
・現在はHamburgerBarとHamburgerMenuの両方のコンポーネントでsetOpenとsetIsOpenのtypeを宣言しexportしているが、片方のコンポーネントではもう片方のコンポーネントのtypeをimportして使った方がいいのか
を教えていただきたいです 💦

2021-09-10 01:08 UTC, mp-gumi commented on src/components/Header/HamburgerBar/index.tsx
> +type HamburgerBarProps = {
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/27c878016dafcbe962d1af695dd7549032ce8dc0
において修正しました。

2021-09-10 01:08 UTC, mp-gumi commented on src/components/Header/HamburgerBar/index.tsx
> +  const { isOpen, setIsOpen } = props;
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/27c878016dafcbe962d1af695dd7549032ce8dc0
において修正しました。

2021-09-10 01:08 UTC, mp-gumi commented on src/components/Header/HamburgerBar/index.tsx
> +  const handleClick = () => {
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/27c878016dafcbe962d1af695dd7549032ce8dc0
において修正しました。

2021-09-10 01:09 UTC, mp-gumi commented on src/components/Header/Logo/index.tsx
> +    <Link to={"/"}>
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/27c878016dafcbe962d1af695dd7549032ce8dc0
において修正しました。

2021-09-10 01:09 UTC, mp-gumi commented on src/components/Header/Menu/index.tsx
> +  const items = [
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/27c878016dafcbe962d1af695dd7549032ce8dc0
において修正しました。

2021-09-10 02:48 UTC, piro0919 commented on src/components/Header/Menu/index.tsx
> +    return [
[imo]

即 return なので return 文が省略できますね。 👍

2021-09-10 02:58 UTC, mp-gumi commented on src/components/Header/Menu/index.tsx
> +    return [
@piro0919 

https://github.com/mp-gumi/training-kaneko-1/pull/16/commits/eb9a5b67112a1a3454c8dd0dff689d5bb769d534
において、MenuとHamburgerMenuの2か所を修正しました。

2021-09-10 03:00 UTC, piro0919 approved these changes
LGTM 👍

2021-09-10 03:00 UTC, merged