feat: delete 5 unnecessary files
mp-gumi/training-kaneko-1 pull request #9
Opened 2021-09-03 07:29 UTC by mp-gumi

close #6

2021-09-03 07:31 UTC, piro0919 requested changes

2021-09-03 07:31 UTC, piro0919 commented on src/index.tsx
>  import './index.css';
[must]

不要ですね。 👀

2021-09-06 03:57 UTC, mp-gumi commented on src/index.tsx
>  import './index.css';
@piro0919

https://github.com/mp-gumi/training-kaneko-1/pull/9/commits/d1dab3ca848a9f7c656711c1d54d90d4baa218c5 において修正しました。 👍

2021-09-06 03:57 UTC, piro0919 approved these changes
LGTM 👍

2021-09-06 03:57 UTC, merged